### PR TITLE
Use standard JDK regex library instead of named-regexp library

### PR DESCRIPTION
**Pull request by norrisjeremy**
Use standard JDK regex library instead of named-regexp library since Java 8+ is required and natively supports [named capture groups](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#groupname).

Additionally, whilst I am not an Android developer, it would appear that named capture groups are also [natively supported](https://developer.android.com/reference/java/util/regex/Pattern#groupname) as of [Android 8.0 (API level 26)](https://developer.android.com/about/versions/oreo/android-8.0). And since this is also the first Android release to support Java 8 (which is now a requirement for 7.x versions of this library), I would assume that using the standard JDK regex library is safe there as well.

### CODE REVIEW

**Comment by bbottema** [comment]
Relates to https://github.com/bbottema/simple-java-mail/pull/343 and https://github.com/bbottema/simple-java-mail/issues/352

**Comment by norrisjeremy** [comment]
Oops, sorry, I should have searched through closed issues & PRs first.
However, since 7.x versions now have a Java 8+ runtime requirement, not sure what the purpose is of using the alternate `named-regexp` library is, since any Android release that supports Java 8+ runtime, also supports named capture groups?
Or perhaps I am misunderstanding?

**Comment by bbottema** [comment]
I was not aware of that actually. So now I'm wondering if I should actually backport this change into a 6.x.x release.

**Comment by norrisjeremy** [comment]
Yes, I suspect using the `named-regexp` library may be more useful for users running 6.x versions, since it presumably supports older Java runtimes and would be more likely to usable with older Android releases (at least, based upon my limited understanding of Android development).

**Pull request merged**
