### PR TITLE
Add option to parse MimeMessage without fetching attachment data from server

### PR DESCRIPTION
**Pull request by drencrom**
I´d like to know of there is some way to parse a `MimeMessage` (like `EmailConverter.mimeMessageToEmail`) that does not read the contents of all attachments. I have a use case where it is useful to have the Email object but the emails have large attachments that take some time to download from the IMAP server and are not needed.
I suppose it is possible to create an Email object that reads the attachment contents only when they are requested, for example by executing the `getAttachments` function.
If this does not exist maybe I will develop it myself unless you think that is not possible for some reason I'm not seeing right now.

Thanks

### CODE REVIEW

**Comment by bbottema** [comment]
I'm mergin this, but I'm changing the behavior a bit. I don't want to return the datasource as-is as it isn't always formed the same way depending on the client that sent it.

So I'm retaining the original behavior with the change that the input stream is not fetched and read to a byte array, but the original input stream is reused. Do you see any issue with this?

```java
InputStream is = retrieveInputStream(dataSource);
ByteArrayDataSource result = fetchAttachmentData
	? new ByteArrayDataSource(readContent(is), contentType)
	 : new ByteArrayDataSource(is, contentType);
```

**Comment by bbottema** [comment]
Released in 6.7.0!

**Comment by drencrom** [comment]
Sorry for the delay in answering. I'm not sure if this change will work. Looking at the code for ByteArrayDataSource:

https://github.com/javaee/javamail/blob/8106b9dd15e917da63e96c33f8c6aea1cad40045/mail/src/main/java/javax/mail/util/ByteArrayDataSource.java#L83

It seems that the constructor reads the InputStream itself. I can confirm this on Monday.

**Comment by bbottema** [comment]
Crap, I think you're right. I did this change quick and dirty in between the maintenance releases. In that case I'm not sure what the middle road is yet...

**Comment by bbottema** [comment]
Ok, I think I have a better solution now, released in 6.7.1. Please have a look when you can.

**Comment by bbottema** [comment]
Follow-up: this custom-`DataSource` lineage now feeds into the v9.2.0 serialization overhaul in #690. Serialization preserves the source's bytes and MIME metadata as a repeatable, read-only snapshot, while explicitly not promising to restore the custom class, lazy/network behavior, caching, or write support.

**Pull request merged**
