### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by rover886**
latest version of the smime-module should refer to utils-mail-smime version 2.3.2.

### CODE REVIEW

**Comment by rover886** [comment]
Hi @bbottema we received an snyk report mentioning  
```
✗ Observable Timing Discrepancy [Medium Severity][https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6277382] in org.bouncycastle:bcprov-jdk15to18@1.75
introduced by org.simplejavamail:smime-module@8.1.3 > org.simplejavamail:utils-mail-smime@2.1.2 > org.bouncycastle:bcjmail-jdk15to18@1.75 > org.bouncycastle:bcprov-jdk15to18@1.75 and 2 other path(s
```

To resolve this we updated smime-module to 8.8.3 but it still not resolved the issue, because 8.8.3 is still referring to utils-mail-smime version 2.3.1 which again refers to version 1.75 of BC. Hence this PR is to bump up the version of utils-mail-smime to 2.3.2 which is latest and which refers to 1.78 version of BC.

**Comment by bbottema** [comment]
I'm in the process of updating a lot of 4rd party dependencies, to solve all transitive known CVE issues. However, I can release a patch version for you in the meantime.

**Comment by bbottema** [comment]
Released in 8.8.4.

**Comment by rover886** [comment]
Tons of thanks @bbottema for taking this effort to release a new version with lighting fast speed.

**Comment by bbottema** [comment]
I just released 8.9.0, see details [here](https://github.com/bbottema/simple-java-mail/issues/507#issuecomment-2079624921).

**Pull request merged**
